In [1]:
# Importing libraries

import numpy as np
import pandas as pd

In [2]:
#loading the file

df=pd.read_csv("C:\\Users\\abypt\\OneDrive\\Documents\\Harkeerat\\DATASETS for projects\\Iris_data_sample.csv")

df.head()

,Unnamed: 0,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,NaN,1.4,0.2,NaN
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,??,3.1,1.5,0.2,Iris-setosa
4,5,5,3.6,###,0.2,Iris-setosa

In [3]:
# To remove the unwanted column
df=pd.read_csv("C:\\Users\\abypt\\OneDrive\\Documents\\Harkeerat\\DATASETS for projects\\Iris_data_sample.csv",index_col=0)

df.head()

  SepalLengthCm  SepalWidthCm PetalLengthCm  PetalWidthCm      Species
1           5.1           3.5           1.4           0.2  Iris-setosa
2           4.9           NaN           1.4           0.2          NaN
3           4.7           3.2           1.3           0.2  Iris-setosa
4            ??           3.1           1.5           0.2  Iris-setosa
5             5           3.6           ###           0.2  Iris-setosa

In [4]:
#missing values
df.isnull().head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
1          False         False          False         False    False
2          False          True          False         False     True
3          False         False          False         False    False
4          False         False          False         False    False
5          False         False          False         False    False

In [5]:
# To count missing values
df.isnull().sum()

SepalLengthCm    0
SepalWidthCm     1
PetalLengthCm    1
PetalWidthCm     0
Species          1
dtype: int64

In [6]:
df=pd.read_csv("C:\\Users\\abypt\\OneDrive\\Documents\\Harkeerat\\DATASETS for projects\\Iris_data_sample.csv",index_col=0, 
               na_values=["??","###"])
df.head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
1            5.1           3.5            1.4           0.2  Iris-setosa
2            4.9           NaN            1.4           0.2          NaN
3            4.7           3.2            1.3           0.2  Iris-setosa
4            NaN           3.1            1.5           0.2  Iris-setosa
5            5.0           3.6            NaN           0.2  Iris-setosa

In [7]:
#Dropping missing values

df.dropna()

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
1              5.1           3.5            1.4           0.2     Iris-setosa
3              4.7           3.2            1.3           0.2     Iris-setosa
7              4.6           3.4            1.4           0.3     Iris-setosa
8              5.0           3.4            1.5           0.2     Iris-setosa
9              4.4           2.9            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
146            6.7           3.0            5.2           2.3  Iris-virginica
147            6.3           2.5            5.0           1.9  Iris-virginica
148            6.5           3.0            5.2           2.0  Iris-virginica
149            6.2           3.4            5.4           2.3  Iris-virginica
150            5.9           3.0            5.1           1.8  Iris-virginica

[146 rows x 5 columns]

In [8]:
#dropping the columns which contain missing values

df.dropna(axis=1)

     PetalWidthCm
1             0.2
2             0.2
3             0.2
4             0.2
5             0.2
..            ...
146           2.3
147           1.9
148           2.0
149           2.3
150           1.8

[150 rows x 1 columns]

In [9]:
# Drop rows with missing values in columns SepalLengthCm and SepalWidthCm. You can specify any number of column
df.dropna(subset=['SepalLengthCm', 'SepalWidthCm'])

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
1              5.1           3.5            1.4           0.2     Iris-setosa
3              4.7           3.2            1.3           0.2     Iris-setosa
5              5.0           3.6            NaN           0.2     Iris-setosa
6              5.4           3.9            NaN           0.4     Iris-setosa
7              4.6           3.4            1.4           0.3     Iris-setosa
..             ...           ...            ...           ...             ...
146            6.7           3.0            5.2           2.3  Iris-virginica
147            6.3           2.5            5.0           1.9  Iris-virginica
148            6.5           3.0            5.2           2.0  Iris-virginica
149            6.2           3.4            5.4           2.3  Iris-virginica
150            5.9           3.0            5.1           1.8  Iris-virginica

[148 rows x 5 columns]

In [10]:
# Drop rows with aleast two missing values
df.dropna(thresh=2)   #unfortunately no row contain two missing values

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
1              5.1           3.5            1.4           0.2     Iris-setosa
2              4.9           NaN            1.4           0.2             NaN
3              4.7           3.2            1.3           0.2     Iris-setosa
4              NaN           3.1            1.5           0.2     Iris-setosa
5              5.0           3.6            NaN           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
146            6.7           3.0            5.2           2.3  Iris-virginica
147            6.3           2.5            5.0           1.9  Iris-virginica
148            6.5           3.0            5.2           2.0  Iris-virginica
149            6.2           3.4            5.4           2.3  Iris-virginica
150            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [11]:
df.fillna('Keep Learning',inplace=True)
df.head()

   SepalLengthCm   SepalWidthCm  PetalLengthCm  PetalWidthCm        Species
1            5.1            3.5            1.4           0.2    Iris-setosa
2            4.9  Keep Learning            1.4           0.2  Keep Learning
3            4.7            3.2            1.3           0.2    Iris-setosa
4  Keep Learning            3.1            1.5           0.2    Iris-setosa
5            5.0            3.6  Keep Learning           0.2    Iris-setosa

In [12]:
#Done a mistake of using inplace=True. the whole dataset get changed. So need to reload it

In [13]:

df=pd.read_csv("C:\\Users\\abypt\\OneDrive\\Documents\\Harkeerat\\DATASETS for projects\\Iris_data_sample.csv",index_col=0, 
               na_values=["??","###"])
#As you can see NaN in row 2,4 and 5
df.head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
1            5.1           3.5            1.4           0.2  Iris-setosa
2            4.9           NaN            1.4           0.2          NaN
3            4.7           3.2            1.3           0.2  Iris-setosa
4            NaN           3.1            1.5           0.2  Iris-setosa
5            5.0           3.6            NaN           0.2  Iris-setosa

In [14]:
df.fillna(0.0,inplace=False)

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
1              5.1           3.5            1.4           0.2     Iris-setosa
2              4.9           0.0            1.4           0.2             0.0
3              4.7           3.2            1.3           0.2     Iris-setosa
4              0.0           3.1            1.5           0.2     Iris-setosa
5              5.0           3.6            0.0           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
146            6.7           3.0            5.2           2.3  Iris-virginica
147            6.3           2.5            5.0           1.9  Iris-virginica
148            6.5           3.0            5.2           2.0  Iris-virginica
149            6.2           3.4            5.4           2.3  Iris-virginica
150            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [15]:
#filling missing values with 0.0
df.fillna(0.0,inplace=False).head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
1            5.1           3.5            1.4           0.2  Iris-setosa
2            4.9           0.0            1.4           0.2          0.0
3            4.7           3.2            1.3           0.2  Iris-setosa
4            0.0           3.1            1.5           0.2  Iris-setosa
5            5.0           3.6            0.0           0.2  Iris-setosa

In [16]:
#Filling missing value with mean.Notice that onl;u numeric values will be updated
df.fillna(df.mean(), inplace=False).head()

C:\Users\abypt\AppData\Local\Temp\ipykernel_25756\4052851017.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.fillna(df.mean(), inplace=False).head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
1       5.100000      3.500000       1.400000           0.2  Iris-setosa
2       4.900000      3.054362       1.400000           0.2          NaN
3       4.700000      3.200000       1.300000           0.2  Iris-setosa
4       5.851678      3.100000       1.500000           0.2  Iris-setosa
5       5.000000      3.600000       3.788514           0.2  Iris-setosa

In [17]:
df.fillna(df.median(), inplace=False).head()

C:\Users\abypt\AppData\Local\Temp\ipykernel_25756\362432479.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.fillna(df.median(), inplace=False).head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
1            5.1           3.5            1.4           0.2  Iris-setosa
2            4.9           3.0            1.4           0.2          NaN
3            4.7           3.2            1.3           0.2  Iris-setosa
4            5.8           3.1            1.5           0.2  Iris-setosa
5            5.0           3.6            4.4           0.2  Iris-setosa

In [18]:
df.head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
1            5.1           3.5            1.4           0.2  Iris-setosa
2            4.9           NaN            1.4           0.2          NaN
3            4.7           3.2            1.3           0.2  Iris-setosa
4            NaN           3.1            1.5           0.2  Iris-setosa
5            5.0           3.6            NaN           0.2  Iris-setosa

In [19]:
# Forward filling
df.fillna(method='ffill', inplace=False).head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
1            5.1           3.5            1.4           0.2  Iris-setosa
2            4.9           3.5            1.4           0.2  Iris-setosa
3            4.7           3.2            1.3           0.2  Iris-setosa
4            4.7           3.1            1.5           0.2  Iris-setosa
5            5.0           3.6            1.5           0.2  Iris-setosa

In [20]:
# Backward filling
df.fillna(method='bfill', inplace=False).head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
1            5.1           3.5            1.4           0.2  Iris-setosa
2            4.9           3.2            1.4           0.2  Iris-setosa
3            4.7           3.2            1.3           0.2  Iris-setosa
4            5.0           3.1            1.5           0.2  Iris-setosa
5            5.0           3.6            1.4           0.2  Iris-setosa

In [21]:
df.head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
1            5.1           3.5            1.4           0.2  Iris-setosa
2            4.9           NaN            1.4           0.2          NaN
3            4.7           3.2            1.3           0.2  Iris-setosa
4            NaN           3.1            1.5           0.2  Iris-setosa
5            5.0           3.6            NaN           0.2  Iris-setosa

In [22]:
df.interpolate(method='linear', inplace=False).head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
1           5.10          3.50       1.400000           0.2  Iris-setosa
2           4.90          3.35       1.400000           0.2          NaN
3           4.70          3.20       1.300000           0.2  Iris-setosa
4           4.85          3.10       1.500000           0.2  Iris-setosa
5           5.00          3.60       1.466667           0.2  Iris-setosa

In [23]:
df.head(10)

    SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
1             5.1           3.5            1.4           0.2  Iris-setosa
2             4.9           NaN            1.4           0.2          NaN
3             4.7           3.2            1.3           0.2  Iris-setosa
4             NaN           3.1            1.5           0.2  Iris-setosa
5             5.0           3.6            NaN           0.2  Iris-setosa
6             5.4           3.9            NaN           0.4  Iris-setosa
7             4.6           3.4            1.4           0.3  Iris-setosa
8             5.0           3.4            1.5           0.2  Iris-setosa
9             4.4           2.9            1.4           0.2  Iris-setosa
10            4.9           3.1            1.5           0.1  Iris-setosa

In [24]:
# Printing all the rows of the dataset
pd.set_option('display.max_rows', None)

# Display the dataset
print(df)

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm          Species
1              5.1           3.5            1.4           0.2      Iris-setosa
2              4.9           NaN            1.4           0.2              NaN
3              4.7           3.2            1.3           0.2      Iris-setosa
4              NaN           3.1            1.5           0.2      Iris-setosa
5              5.0           3.6            NaN           0.2      Iris-setosa
6              5.4           3.9            NaN           0.4      Iris-setosa
7              4.6           3.4            1.4           0.3      Iris-setosa
8              5.0           3.4            1.5           0.2      Iris-setosa
9              4.4           2.9            1.4           0.2      Iris-setosa
10             4.9           3.1            1.5           0.1      Iris-setosa
11             5.4           3.7            1.5           0.2      Iris-setosa
12             4.8           3.4            1.6           0.2      Iris-setosa
13             4.8           3.0            1.4           0.1      Iris-setosa
14             4.3           3.0            1.1           0.1      Iris-setosa
15             5.8           4.0            1.2           0.2      Iris-setosa
16             5.7           4.4            1.5           0.4      Iris-setosa
17             5.4           3.9            1.3           0.4      Iris-setosa
18             5.1           3.5            1.4           0.3      Iris-setosa
19             5.7           3.8            1.7           0.3      Iris-setosa
20             5.1           3.8            1.5           0.3      Iris-setosa
21             5.4           3.4            1.7           0.2      Iris-setosa
22             5.1           3.7            1.5           0.4      Iris-setosa
23             4.6           3.6            1.0           0.2      Iris-setosa
24             5.1           3.3            1.7           0.5      Iris-setosa
25             4.8           3.4            1.9           0.2      Iris-setosa
26             5.0           3.0            1.6           0.2      Iris-setosa
27             5.0           3.4            1.6           0.4      Iris-setosa
28             5.2           3.5            1.5           0.2      Iris-setosa
29             5.2           3.4            1.4           0.2      Iris-setosa
30             4.7           3.2            1.6           0.2      Iris-setosa
31             4.8           3.1            1.6           0.2      Iris-setosa
32             5.4           3.4            1.5           0.4      Iris-setosa
33             5.2           4.1            1.5           0.1      Iris-setosa
34             5.5           4.2            1.4           0.2      Iris-setosa
35             4.9           3.1            1.5           0.1      Iris-setosa
36             5.0           3.2            1.2           0.2      Iris-setosa
37             5.5           3.5            1.3           0.2      Iris-setosa
38             4.9           3.1            1.5           0.1      Iris-setosa
39             4.4           3.0            1.3           0.2      Iris-setosa
40             5.1           3.4            1.5           0.2      Iris-setosa
41             5.0           3.5            1.3           0.3      Iris-setosa
42             4.5           2.3            1.3           0.3      Iris-setosa
43             4.4           3.2            1.3           0.2      Iris-setosa
44             5.0           3.5            1.6           0.6      Iris-setosa
45             5.1           3.8            1.9           0.4      Iris-setosa
46             4.8           3.0            1.4           0.3      Iris-setosa
47             5.1           3.8            1.6           0.2      Iris-setosa
48             4.6           3.2            1.4           0.2      Iris-setosa
49             5.3           3.7            1.5           0.2      Iris-setosa
50             5.0           3.3            1.4           0.2      Iris-setosa
51             7.0           3.2            4.7           1.4  Iris-versicolor
52             6.4           3.2            4.5           1.5  Iris-versicolor
53             6.9           3.1            4.9           1.5  Iris-versicolor
54             5.5           2.3            4.0           1.3  Iris-versicolor
55             6.5           2.8            4.6           1.5  Iris-versicolor
56             5.7           2.8            4.5           1.3  Iris-versicolor
57             6.3           3.3            4.7           1.6  Iris-versicolor
58             4.9           2.4            3.3           1.0  Iris-versicolor
59             6.6           2.9            4.6           1.3  Iris-versicolor
60             5.2           2.7            3.9           1.4  Iris-versicolor
61             5.0           2.0            3.5           1.0  Iris-versicolor
62             5.9           3.0            4.2           1.5  Iris-versicolor
63             6.0           2.2            4.0           1.0  Iris-versicolor
64             6.1           2.9            4.7           1.4  Iris-versicolor
65             5.6           2.9            3.6           1.3  Iris-versicolor
66             6.7           3.1            4.4           1.4  Iris-versicolor
67             5.6           3.0            4.5           1.5  Iris-versicolor
68             5.8           2.7            4.1           1.0  Iris-versicolor
69             6.2           2.2            4.5           1.5  Iris-versicolor
70             5.6           2.5            3.9           1.1  Iris-versicolor
71             5.9           3.2            4.8           1.8  Iris-versicolor
72             6.1           2.8            4.0           1.3  Iris-versicolor
73             6.3           2.5            4.9           1.5  Iris-versicolor
74             6.1           2.8            4.7           1.2  Iris-versicolor
75             6.4           2.9            4.3           1.3  Iris-versicolor
76             6.6           3.0            4.4           1.4  Iris-versicolor
77             6.8           2.8            4.8           1.4  Iris-versicolor
78             6.7           3.0            5.0           1.7  Iris-versicolor
79             6.0           2.9            4.5           1.5  Iris-versicolor
80             5.7           2.6            3.5           1.0  Iris-versicolor
81             5.5           2.4            3.8           1.1  Iris-versicolor
82             5.5           2.4            3.7           1.0  Iris-versicolor
83             5.8           2.7            3.9           1.2  Iris-versicolor
84             6.0           2.7            5.1           1.6  Iris-versicolor
85             5.4           3.0            4.5           1.5  Iris-versicolor
86             6.0           3.4            4.5           1.6  Iris-versicolor
87             6.7           3.1            4.7           1.5  Iris-versicolor
88             6.3           2.3            4.4           1.3  Iris-versicolor
89             5.6           3.0            4.1           1.3  Iris-versicolor
90             5.5           2.5            4.0           1.3  Iris-versicolor
91             5.5           2.6            4.4           1.2  Iris-versicolor
92             6.1           3.0            4.6           1.4  Iris-versicolor
93             5.8           2.6            4.0           1.2  Iris-versicolor
94             5.0           2.3            3.3           1.0  Iris-versicolor
95             5.6           2.7            4.2           1.3  Iris-versicolor
96             5.7           3.0            4.2           1.2  Iris-versicolor
97             5.7           2.9            4.2           1.3  Iris-versicolor
98             6.2           2.9            4.3           1.3  Iris-versicolor
99             5.1           2.5            3.0           1.1  Iris-versicolor
100            5.7           2.8            4.1           1.3  Iris-versicolor
101            6.3           3.3            6.0           2.5   Iris-virginica
102            5.8           2.7            5.1           1.9   Iris-virginica
103            7.1           3.0            5.9           2.1   Iris-virginica
104            6.3           2.9            5.6           1.8   Iris-virginica
105            6.5           3.0            5.8           2.2   Iris-virginica
106            7.6           3.0            6.6           2.1   Iris-virginica
107            4.9           2.5            4.5           1.7   Iris-virginica
108            7.3           2.9            6.3           1.8   Iris-virginica
109            6.7           2.5            5.8           1.8   Iris-virginica
110            7.2           3.6            6.1           2.5   Iris-virginica
111            6.5           3.2            5.1           2.0   Iris-virginica
112            6.4           2.7            5.3           1.9   Iris-virginica
113            6.8           3.0            5.5           2.1   Iris-virginica
114            5.7           2.5            5.0           2.0   Iris-virginica
115            5.8           2.8            5.1           2.4   Iris-virginica
116            6.4           3.2            5.3           2.3   Iris-virginica
117            6.5           3.0            5.5           1.8   Iris-virginica
118            7.7           3.8            6.7           2.2   Iris-virginica
119            7.7           2.6            6.9           2.3   Iris-virginica
120            6.0           2.2            5.0           1.5   Iris-virginica
121            6.9           3.2            5.7           2.3   Iris-virginica
122            5.6           2.8            4.9           2.0   Iris-virginica
123            7.7           2.8            6.7           2.0   Iris-virginica
124            6.3           2.7            4.9           1.8   Iris-virginica
125            6.7           3.3            5.7           2.1   Iris-virginica
126            7.2           3.2            6.0           1.8   Iris-virginica
127            6.2           2.8            4.8           1.8   Iris-virginica
128            6.1           3.0            4.9           1.8   Iris-virginica
129            6.4           2.8            5.6           2.1   Iris-virginica
130            7.2           3.0            5.8           1.6   Iris-virginica
131            7.4           2.8            6.1           1.9   Iris-virginica
132            7.9           3.8            6.4           2.0   Iris-virginica
133            6.4           2.8            5.6           2.2   Iris-virginica
134            6.3           2.8            5.1           1.5   Iris-virginica
135            6.1           2.6            5.6           1.4   Iris-virginica
136            7.7           3.0            6.1           2.3   Iris-virginica
137            6.3           3.4            5.6           2.4   Iris-virginica
138            6.4           3.1            5.5           1.8   Iris-virginica
139            6.0           3.0            4.8           1.8   Iris-virginica
140            6.9           3.1            5.4           2.1   Iris-virginica
141            6.7           3.1            5.6           2.4   Iris-virginica
142            6.9           3.1            5.1           2.3   Iris-virginica
143            5.8           2.7            5.1           1.9   Iris-virginica
144            6.8           3.2            5.9           2.3   Iris-virginica
145            6.7           3.3            5.7           2.5   Iris-virginica
146            6.7           3.0            5.2           2.3   Iris-virginica
147            6.3           2.5            5.0           1.9   Iris-virginica
148            6.5           3.0            5.2           2.0   Iris-virginica
149            6.2           3.4            5.4           2.3   Iris-virginica
150            5.9           3.0            5.1           1.8   Iris-virginica

In [25]:
df.duplicated()

1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
30     False
31     False
32     False
33     False
34     False
35      True
36     False
37     False
38      True
39     False
40     False
41     False
42     False
43     False
44     False
45     False
46     False
47     False
48     False
49     False
50     False
51     False
52     False
53     False
54     False
55     False
56     False
57     False
58     False
59     False
60     False
61     False
62     False
63     False
64     False
65     False
66     False
67     False
68     False
69     False
70     False
71     False
72     False
73     False
74     False
75     False
76     False
77     False
78     False
79     False
80     False
81     False
82     False
83     False
84     False
85     False
86     False
87     False
88     False
89     False
90     False
91     False
92     False
93     False
94     False
95     False
96     False
97     False
98     False
99     False
100    False
101    False
102    False
103    False
104    False
105    False
106    False
107    False
108    False
109    False
110    False
111    False
112    False
113    False
114    False
115    False
116    False
117    False
118    False
119    False
120    False
121    False
122    False
123    False
124    False
125    False
126    False
127    False
128    False
129    False
130    False
131    False
132    False
133    False
134    False
135    False
136    False
137    False
138    False
139    False
140    False
141    False
142    False
143     True
144    False
145    False
146    False
147    False
148    False
149    False
150    False
dtype: bool

In [26]:

df.duplicated().sum()

3

In [27]:
# Dropping the duplicate values
df.drop_duplicates()

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm          Species
1              5.1           3.5            1.4           0.2      Iris-setosa
2              4.9           NaN            1.4           0.2              NaN
3              4.7           3.2            1.3           0.2      Iris-setosa
4              NaN           3.1            1.5           0.2      Iris-setosa
5              5.0           3.6            NaN           0.2      Iris-setosa
6              5.4           3.9            NaN           0.4      Iris-setosa
7              4.6           3.4            1.4           0.3      Iris-setosa
8              5.0           3.4            1.5           0.2      Iris-setosa
9              4.4           2.9            1.4           0.2      Iris-setosa
10             4.9           3.1            1.5           0.1      Iris-setosa
11             5.4           3.7            1.5           0.2      Iris-setosa
12             4.8           3.4            1.6           0.2      Iris-setosa
13             4.8           3.0            1.4           0.1      Iris-setosa
14             4.3           3.0            1.1           0.1      Iris-setosa
15             5.8           4.0            1.2           0.2      Iris-setosa
16             5.7           4.4            1.5           0.4      Iris-setosa
17             5.4           3.9            1.3           0.4      Iris-setosa
18             5.1           3.5            1.4           0.3      Iris-setosa
19             5.7           3.8            1.7           0.3      Iris-setosa
20             5.1           3.8            1.5           0.3      Iris-setosa
21             5.4           3.4            1.7           0.2      Iris-setosa
22             5.1           3.7            1.5           0.4      Iris-setosa
23             4.6           3.6            1.0           0.2      Iris-setosa
24             5.1           3.3            1.7           0.5      Iris-setosa
25             4.8           3.4            1.9           0.2      Iris-setosa
26             5.0           3.0            1.6           0.2      Iris-setosa
27             5.0           3.4            1.6           0.4      Iris-setosa
28             5.2           3.5            1.5           0.2      Iris-setosa
29             5.2           3.4            1.4           0.2      Iris-setosa
30             4.7           3.2            1.6           0.2      Iris-setosa
31             4.8           3.1            1.6           0.2      Iris-setosa
32             5.4           3.4            1.5           0.4      Iris-setosa
33             5.2           4.1            1.5           0.1      Iris-setosa
34             5.5           4.2            1.4           0.2      Iris-setosa
36             5.0           3.2            1.2           0.2      Iris-setosa
37             5.5           3.5            1.3           0.2      Iris-setosa
39             4.4           3.0            1.3           0.2      Iris-setosa
40             5.1           3.4            1.5           0.2      Iris-setosa
41             5.0           3.5            1.3           0.3      Iris-setosa
42             4.5           2.3            1.3           0.3      Iris-setosa
43             4.4           3.2            1.3           0.2      Iris-setosa
44             5.0           3.5            1.6           0.6      Iris-setosa
45             5.1           3.8            1.9           0.4      Iris-setosa
46             4.8           3.0            1.4           0.3      Iris-setosa
47             5.1           3.8            1.6           0.2      Iris-setosa
48             4.6           3.2            1.4           0.2      Iris-setosa
49             5.3           3.7            1.5           0.2      Iris-setosa
50             5.0           3.3            1.4           0.2      Iris-setosa
51             7.0           3.2            4.7           1.4  Iris-versicolor
52             6.4           3.2            4.5           1.5  Iris-versicolor
53             6.9           3.1            4.9           1.5  Iris-versicolor
54             5.5           2.3            4.0           1.3  Iris-versicolor
55             6.5           2.8            4.6           1.5  Iris-versicolor
56             5.7           2.8            4.5           1.3  Iris-versicolor
57             6.3           3.3            4.7           1.6  Iris-versicolor
58             4.9           2.4            3.3           1.0  Iris-versicolor
59             6.6           2.9            4.6           1.3  Iris-versicolor
60             5.2           2.7            3.9           1.4  Iris-versicolor
61             5.0           2.0            3.5           1.0  Iris-versicolor
62             5.9           3.0            4.2           1.5  Iris-versicolor
63             6.0           2.2            4.0           1.0  Iris-versicolor
64             6.1           2.9            4.7           1.4  Iris-versicolor
65             5.6           2.9            3.6           1.3  Iris-versicolor
66             6.7           3.1            4.4           1.4  Iris-versicolor
67             5.6           3.0            4.5           1.5  Iris-versicolor
68             5.8           2.7            4.1           1.0  Iris-versicolor
69             6.2           2.2            4.5           1.5  Iris-versicolor
70             5.6           2.5            3.9           1.1  Iris-versicolor
71             5.9           3.2            4.8           1.8  Iris-versicolor
72             6.1           2.8            4.0           1.3  Iris-versicolor
73             6.3           2.5            4.9           1.5  Iris-versicolor
74             6.1           2.8            4.7           1.2  Iris-versicolor
75             6.4           2.9            4.3           1.3  Iris-versicolor
76             6.6           3.0            4.4           1.4  Iris-versicolor
77             6.8           2.8            4.8           1.4  Iris-versicolor
78             6.7           3.0            5.0           1.7  Iris-versicolor
79             6.0           2.9            4.5           1.5  Iris-versicolor
80             5.7           2.6            3.5           1.0  Iris-versicolor
81             5.5           2.4            3.8           1.1  Iris-versicolor
82             5.5           2.4            3.7           1.0  Iris-versicolor
83             5.8           2.7            3.9           1.2  Iris-versicolor
84             6.0           2.7            5.1           1.6  Iris-versicolor
85             5.4           3.0            4.5           1.5  Iris-versicolor
86             6.0           3.4            4.5           1.6  Iris-versicolor
87             6.7           3.1            4.7           1.5  Iris-versicolor
88             6.3           2.3            4.4           1.3  Iris-versicolor
89             5.6           3.0            4.1           1.3  Iris-versicolor
90             5.5           2.5            4.0           1.3  Iris-versicolor
91             5.5           2.6            4.4           1.2  Iris-versicolor
92             6.1           3.0            4.6           1.4  Iris-versicolor
93             5.8           2.6            4.0           1.2  Iris-versicolor
94             5.0           2.3            3.3           1.0  Iris-versicolor
95             5.6           2.7            4.2           1.3  Iris-versicolor
96             5.7           3.0            4.2           1.2  Iris-versicolor
97             5.7           2.9            4.2           1.3  Iris-versicolor
98             6.2           2.9            4.3           1.3  Iris-versicolor
99             5.1           2.5            3.0           1.1  Iris-versicolor
100            5.7           2.8            4.1           1.3  Iris-versicolor
101            6.3           3.3            6.0           2.5   Iris-virginica
102            5.8           2.7            5.1           1.9   Iris-virginica
103            7.1           3.0            5.9           2.1   Iris-virginica
104            6.3           2.9            5.6           1.8   Iris-virginica
105            6.5           3.0            5.8           2.2   Iris-virginica
106            7.6           3.0            6.6           2.1   Iris-virginica
107            4.9           2.5            4.5           1.7   Iris-virginica
108            7.3           2.9            6.3           1.8   Iris-virginica
109            6.7           2.5            5.8           1.8   Iris-virginica
110            7.2           3.6            6.1           2.5   Iris-virginica
111            6.5           3.2            5.1           2.0   Iris-virginica
112            6.4           2.7            5.3           1.9   Iris-virginica
113            6.8           3.0            5.5           2.1   Iris-virginica
114            5.7           2.5            5.0           2.0   Iris-virginica
115            5.8           2.8            5.1           2.4   Iris-virginica
116            6.4           3.2            5.3           2.3   Iris-virginica
117            6.5           3.0            5.5           1.8   Iris-virginica
118            7.7           3.8            6.7           2.2   Iris-virginica
119            7.7           2.6            6.9           2.3   Iris-virginica
120            6.0           2.2            5.0           1.5   Iris-virginica
121            6.9           3.2            5.7           2.3   Iris-virginica
122            5.6           2.8            4.9           2.0   Iris-virginica
123            7.7           2.8            6.7           2.0   Iris-virginica
124            6.3           2.7            4.9           1.8   Iris-virginica
125            6.7           3.3            5.7           2.1   Iris-virginica
126            7.2           3.2            6.0           1.8   Iris-virginica
127            6.2           2.8            4.8           1.8   Iris-virginica
128            6.1           3.0            4.9           1.8   Iris-virginica
129            6.4           2.8            5.6           2.1   Iris-virginica
130            7.2           3.0            5.8           1.6   Iris-virginica
131            7.4           2.8            6.1           1.9   Iris-virginica
132            7.9           3.8            6.4           2.0   Iris-virginica
133            6.4           2.8            5.6           2.2   Iris-virginica
134            6.3           2.8            5.1           1.5   Iris-virginica
135            6.1           2.6            5.6           1.4   Iris-virginica
136            7.7           3.0            6.1           2.3   Iris-virginica
137            6.3           3.4            5.6           2.4   Iris-virginica
138            6.4           3.1            5.5           1.8   Iris-virginica
139            6.0           3.0            4.8           1.8   Iris-virginica
140            6.9           3.1            5.4           2.1   Iris-virginica
141            6.7           3.1            5.6           2.4   Iris-virginica
142            6.9           3.1            5.1           2.3   Iris-virginica
144            6.8           3.2            5.9           2.3   Iris-virginica
145            6.7           3.3            5.7           2.5   Iris-virginica
146            6.7           3.0            5.2           2.3   Iris-virginica
147            6.3           2.5            5.0           1.9   Iris-virginica
148            6.5           3.0            5.2           2.0   Iris-virginica
149            6.2           3.4            5.4           2.3   Iris-virginica
150            5.9           3.0            5.1           1.8   Iris-virginica

In [28]:
# Detect outliers

df.describe()

       SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count     149.000000    149.000000     148.000000    150.000000
mean        5.851678      3.054362       3.788514      1.198667
std         0.824507      0.435034       1.757260      0.763161
min         4.300000      2.000000       1.000000      0.100000
25%         5.100000      2.800000       1.600000      0.300000
50%         5.800000      3.000000       4.400000      1.300000
75%         6.400000      3.300000       5.100000      1.800000
max         7.900000      4.400000       6.900000      2.500000